name: KteRising2
version: '2.0.0-BETA'
main: com.kteproject.kterising.KteRising
api-version: '1.20'
authors: [ Ben Lordlex and AlwaysRuby (KteProject) ]
description: LavaRising Plugin
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
commands:
  kterising:
    description: "KteRising is the best!"